[tools]
node = "24"
deno = "2.4.1"

[env]
# silence warnings from CDK about node versions
JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION = true

[tasks."build:container:local"]
dir = "{{ config_root }}/nestjs"
run = """
  docker buildx build -t flicker-ai-nestjs \
    --cache-to type=local,dest="$HOME"/container/cache/flicket-ai-slackapp \
    --cache-from type=local,src="$HOME"/container/cache/flicket-ai-slackapp \
    .
"""
